### ISSUE TITLE
add examples on how to customize diff appearance

### ISSUE THREAD

**Issue by samu** [samu/git-diff-details#52]
```less
atom-text-editor::shadow .line {
  &.git-diff-details-new-highlighted {
    background-color: rgba(162, 232, 120, 0.3) !important;
  }

  &.git-diff-details-old-highlighted {
    background-color: rgba(232, 120, 120, 0.2) !important;
  }

  &.git-diff-details-new-flat {
    background-color: rgba(162, 232, 120, 0.7) !important;
  }

  &.git-diff-details-old-flat {
    background-color: rgba(232, 120, 120, 0.7) !important;
  }
}
```
